(function initFdtdUiDom(global) {
  "use strict";

  const REQUIRED_REF_KEYS = Object.freeze([
    "canvas",
    "canvasFrame",
    "stage",
    "canvasToolbar",
    "appShell",
    "controlPanel",
    "controlDrawerToggle",
    "controlDrawerCloseBtn",
    "controlDrawerBackdrop",
    "controlTabButtons",
    "controlTabPanels",
    "mobileLayerButtons",
    "themeButtons",
    "playPauseBtn",
    "playPauseIcon",
    "resetBtn",
    "selectModeBtn",
    "brushModeBtn",
    "presetInput",
    "sceneCards",
    "sceneGuidePanel",
    "colorbar",
  ]);

  function refIsMissing(value) {
    if (!value) return true;
    if (typeof value.length === "number" && value.nodeType == null && typeof value !== "string") {
      return value.length === 0;
    }
    return false;
  }

  function validateDomRefs(refs, requiredKeys = REQUIRED_REF_KEYS) {
    const missing = requiredKeys.filter((key) => refIsMissing(refs[key]));
    if (missing.length > 0) {
      throw new Error(`Missing required UI element(s): ${missing.join(", ")}`);
    }
    return refs;
  }

  function collectDomRefs(documentRef = global.document) {
    return {
      canvas: documentRef.getElementById("simCanvas"),
      canvasFrame: documentRef.querySelector(".canvas-frame"),
      stage: documentRef.querySelector(".stage"),
      canvasToolbar: documentRef.querySelector(".canvas-toolbar"),
      canvasActionMenu: documentRef.getElementById("canvasActionMenu"),
      canvasActionToggle: documentRef.getElementById("canvasActionToggle"),
      canvasViewControls: documentRef.getElementById("canvasViewControls"),
      canvasOptionsToggle: documentRef.getElementById("canvasOptionsToggle"),
      appShell: documentRef.querySelector(".app-shell"),
      controlPanel: documentRef.getElementById("controlPanel"),
      controlPanelKicker: documentRef.getElementById("controlPanelKicker"),
      controlPanelTitle: documentRef.getElementById("controlPanelTitle"),
      controlDrawerToggle: documentRef.getElementById("controlDrawerToggle"),
      controlDrawerCloseBtn: documentRef.getElementById("controlDrawerCloseBtn"),
      controlDrawerBackdrop: documentRef.getElementById("controlDrawerBackdrop"),
      controlTabButtons: documentRef.querySelectorAll("[data-control-tab]"),
      controlTabPanels: documentRef.querySelectorAll("[data-control-panel]"),
      mobileLayerButtons: documentRef.querySelectorAll(".mobile-layer-button[data-mobile-layer]"),
      themeButtons: documentRef.querySelectorAll("[data-theme-choice]"),
      uiDepthButtons: documentRef.querySelectorAll("[data-ui-depth-choice]"),
      fieldComponentButtons: documentRef.querySelectorAll("[data-field-component]"),
      viewModeButtons: documentRef.querySelectorAll("[data-view-mode]"),
      fieldViewButton: documentRef.querySelector('[data-view-mode="field"]'),
      fieldDisplayControl: documentRef.getElementById("fieldDisplayControl"),
      fieldDisplayButtons: documentRef.querySelectorAll("[data-field-display]"),
      fieldQuiverControl: documentRef.getElementById("fieldQuiverControl"),
      fieldQuiverInput: documentRef.getElementById("fieldQuiverInput"),
      fieldQuiverLabel: documentRef.getElementById("fieldQuiverLabel"),
      fieldQuiverControls: documentRef.querySelectorAll("[data-field-quiver-control]"),
      fieldQuiverInputs: documentRef.querySelectorAll("[data-field-quiver-input]"),
      fieldQuiverLabels: documentRef.querySelectorAll("[data-field-quiver-label]"),
      visualProfileButtons: documentRef.querySelectorAll("[data-visual-profile]"),
      visualLayerInputs: documentRef.querySelectorAll("[data-visual-layer]"),
      visualGuideProfile: documentRef.getElementById("visualGuideProfile"),
      visualGuideProjection: documentRef.getElementById("visualGuideProjection"),
      visualGuideField: documentRef.getElementById("visualGuideField"),
      visualGuideScale: documentRef.getElementById("visualGuideScale"),
      visualGuideOverlays: documentRef.getElementById("visualGuideOverlays"),
      visualGuideNote: documentRef.getElementById("visualGuideNote"),
      visualComponentRows: documentRef.querySelectorAll(".visual-component-row"),
      viewProjectionButtons: documentRef.querySelectorAll("[data-view-projection]"),
      materialPartControl: documentRef.getElementById("materialPartControl"),
      materialPartButtons: documentRef.querySelectorAll("[data-material-part]"),
      playPauseBtn: documentRef.getElementById("playPauseBtn"),
      playPauseIcon: documentRef.getElementById("playPauseIcon"),
      stepBtn: documentRef.getElementById("stepBtn"),
      resetBtn: documentRef.getElementById("resetBtn"),
      runStepBtn: documentRef.getElementById("runStepBtn"),
      runResetBtn: documentRef.getElementById("runResetBtn"),
      focusControlsBtn: documentRef.getElementById("focusControlsBtn"),
      saveBtn: documentRef.getElementById("saveBtn"),
      selectModeBtn: documentRef.getElementById("selectModeBtn"),
      brushModeBtn: documentRef.getElementById("brushModeBtn"),
      speedInput: documentRef.getElementById("speedInput"),
      speedOutput: documentRef.getElementById("speedOutput"),
      gainInput: documentRef.getElementById("gainInput"),
      gainOutput: documentRef.getElementById("gainOutput"),
      autoScaleInput: documentRef.getElementById("autoScaleInput"),
      diagnosticsInput: documentRef.getElementById("diagnosticsInput"),
      diagnosticsResetBtn: documentRef.getElementById("diagnosticsResetBtn"),
      performanceBackendOutput: documentRef.getElementById("performanceBackendOutput"),
      performanceGridOutput: documentRef.getElementById("performanceGridOutput"),
      performanceStepOutput: documentRef.getElementById("performanceStepOutput"),
      performanceRenderOutput: documentRef.getElementById("performanceRenderOutput"),
      performanceRenderMapOutput: documentRef.getElementById("performanceRenderMapOutput"),
      performanceRenderPresentOutput: documentRef.getElementById("performanceRenderPresentOutput"),
      performanceRenderOverlayOutput: documentRef.getElementById("performanceRenderOverlayOutput"),
      performanceMeasureOutput: documentRef.getElementById("performanceMeasureOutput"),
      performanceThroughputOutput: documentRef.getElementById("performanceThroughputOutput"),
      performanceStatus: documentRef.getElementById("performanceStatus"),
      performanceResetBtn: documentRef.getElementById("performanceResetBtn"),
      resultsStateOutput: documentRef.getElementById("resultsStateOutput"),
      resultsInsightNote: documentRef.getElementById("resultsInsightNote"),
      resultsDetailPanels: documentRef.querySelectorAll(".results-detail-panel"),
      sweepModeInput: documentRef.getElementById("sweepModeInput"),
      sweepStartInput: documentRef.getElementById("sweepStartInput"),
      sweepEndInput: documentRef.getElementById("sweepEndInput"),
      sweepSamplesInput: documentRef.getElementById("sweepSamplesInput"),
      sweepStepsInput: documentRef.getElementById("sweepStepsInput"),
      sweepBidirectionalInput: documentRef.getElementById("sweepBidirectionalInput"),
      sweepRunBtn: documentRef.getElementById("sweepRunBtn"),
      sweepExportBtn: documentRef.getElementById("sweepExportBtn"),
      sweepStatus: documentRef.getElementById("sweepStatus"),
      sweepChart: documentRef.getElementById("sweepChart"),
      sweepChartReadout: documentRef.getElementById("sweepChartReadout"),
      analysisInput: documentRef.getElementById("analysisInput"),
      analysisResetBtn: documentRef.getElementById("analysisResetBtn"),
      analysisStatus: documentRef.getElementById("analysisStatus"),
      spectrumChart: documentRef.getElementById("spectrumChart"),
      farFieldChart: documentRef.getElementById("farFieldChart"),
      analysisChartReadout: documentRef.getElementById("analysisChartReadout"),
      sourceTypeInput: documentRef.getElementById("sourceTypeInput"),
      sourceShapeInput: documentRef.getElementById("sourceShapeInput"),
      frequencyInput: documentRef.getElementById("frequencyInput"),
      frequencyOutput: documentRef.getElementById("frequencyOutput"),
      sourceAmplitudeLabel: documentRef.getElementById("sourceAmplitudeLabel"),
      amplitudeInput: documentRef.getElementById("amplitudeInput"),
      amplitudeOutput: documentRef.getElementById("amplitudeOutput"),
      sourceXInput: documentRef.getElementById("sourceXInput"),
      sourceYInput: documentRef.getElementById("sourceYInput"),
      sourceWidthControl: documentRef.getElementById("sourceWidthControl"),
      sourceWidthInput: documentRef.getElementById("sourceWidthInput"),
      sourceWidthOutput: documentRef.getElementById("sourceWidthOutput"),
      sourceAngleControl: documentRef.getElementById("sourceAngleControl"),
      sourceAngleInput: documentRef.getElementById("sourceAngleInput"),
      sourceAngleOutput: documentRef.getElementById("sourceAngleOutput"),
      sourceTimePhaseControl: documentRef.getElementById("sourceTimePhaseControl"),
      sourceTimePhaseInput: documentRef.getElementById("sourceTimePhaseInput"),
      sourceTimePhaseOutput: documentRef.getElementById("sourceTimePhaseOutput"),
      sourceOrderControl: documentRef.getElementById("sourceOrderControl"),
      sourceOrderInput: documentRef.getElementById("sourceOrderInput"),
      sourcePhaseControl: documentRef.getElementById("sourcePhaseControl"),
      sourcePhaseInput: documentRef.getElementById("sourcePhaseInput"),
      wavelengthInput: documentRef.getElementById("wavelengthInput"),
      cellsPerWavelengthInput: documentRef.getElementById("cellsPerWavelengthInput"),
      customAnisotropyInput: documentRef.getElementById("customAnisotropyInput"),
      brushMaterialGrid: documentRef.getElementById("brushMaterialGrid"),
      customEpsRealLabel: documentRef.getElementById("customEpsRealLabel"),
      customEpsImagLabel: documentRef.getElementById("customEpsImagLabel"),
      customMuRealLabel: documentRef.getElementById("customMuRealLabel"),
      customMuImagLabel: documentRef.getElementById("customMuImagLabel"),
      customEpsRealInput: documentRef.getElementById("customEpsRealInput"),
      customEpsImagInput: documentRef.getElementById("customEpsImagInput"),
      customEpsYRealInput: documentRef.getElementById("customEpsYRealInput"),
      customEpsYImagInput: documentRef.getElementById("customEpsYImagInput"),
      customMuRealInput: documentRef.getElementById("customMuRealInput"),
      customMuImagInput: documentRef.getElementById("customMuImagInput"),
      customMuYRealInput: documentRef.getElementById("customMuYRealInput"),
      customMuYImagInput: documentRef.getElementById("customMuYImagInput"),
      gyrotropyEnabledInput: documentRef.getElementById("gyrotropyEnabledInput"),
      gyrotropyGInput: documentRef.getElementById("gyrotropyGInput"),
      bianisotropyEnabledInput: documentRef.getElementById("bianisotropyEnabledInput"),
      bianisotropyKappaInput: documentRef.getElementById("bianisotropyKappaInput"),
      modulationEnabledInput: documentRef.getElementById("modulationEnabledInput"),
      modulationDepthInput: documentRef.getElementById("modulationDepthInput"),
      modulationFrequencyInput: documentRef.getElementById("modulationFrequencyInput"),
      modulationPeriodInput: documentRef.getElementById("modulationPeriodInput"),
      modulationAngleInput: documentRef.getElementById("modulationAngleInput"),
      modulationPhaseInput: documentRef.getElementById("modulationPhaseInput"),
      nonlinearEnabledInput: documentRef.getElementById("nonlinearEnabledInput"),
      kerrChi3Input: documentRef.getElementById("kerrChi3Input"),
      kerrSaturationInput: documentRef.getElementById("kerrSaturationInput"),
      harmonicEnabledInput: documentRef.getElementById("harmonicEnabledInput"),
      harmonicChi2Input: documentRef.getElementById("harmonicChi2Input"),
      harmonicChi3Input: documentRef.getElementById("harmonicChi3Input"),
      harmonicSaturationInput: documentRef.getElementById("harmonicSaturationInput"),
      phaseChangeEnabledInput: documentRef.getElementById("phaseChangeEnabledInput"),
      phaseEpsOnInput: documentRef.getElementById("phaseEpsOnInput"),
      phaseLossOnInput: documentRef.getElementById("phaseLossOnInput"),
      phaseThresholdOnInput: documentRef.getElementById("phaseThresholdOnInput"),
      phaseThresholdOffInput: documentRef.getElementById("phaseThresholdOffInput"),
      phaseTauOnInput: documentRef.getElementById("phaseTauOnInput"),
      phaseTauOffInput: documentRef.getElementById("phaseTauOffInput"),
      conductivityEnabledInput: documentRef.getElementById("conductivityEnabledInput"),
      conductivitySigmaInput: documentRef.getElementById("conductivitySigmaInput"),
      conductivitySigmaYControl: documentRef.getElementById("conductivitySigmaYControl"),
      conductivitySigmaYInput: documentRef.getElementById("conductivitySigmaYInput"),
      saturableGainEnabledInput: documentRef.getElementById("saturableGainEnabledInput"),
      gainSaturationInput: documentRef.getElementById("gainSaturationInput"),
      dispersionModelInput: documentRef.getElementById("dispersionModelInput"),
      dispersionOmegaPControl: documentRef.getElementById("dispersionOmegaPControl"),
      dispersionOmegaPInput: documentRef.getElementById("dispersionOmegaPInput"),
      dispersionGammaControl: documentRef.getElementById("dispersionGammaControl"),
      dispersionGammaInput: documentRef.getElementById("dispersionGammaInput"),
      dispersionOmega0Control: documentRef.getElementById("dispersionOmega0Control"),
      dispersionOmega0Input: documentRef.getElementById("dispersionOmega0Input"),
      dispersionDeltaEpsControl: documentRef.getElementById("dispersionDeltaEpsControl"),
      dispersionDeltaEpsInput: documentRef.getElementById("dispersionDeltaEpsInput"),
      dispersionTauControl: documentRef.getElementById("dispersionTauControl"),
      dispersionTauInput: documentRef.getElementById("dispersionTauInput"),
      materialWarning: documentRef.getElementById("materialWarning"),
      presetInput: documentRef.getElementById("presetInput"),
      sceneSearchInput: documentRef.getElementById("sceneSearchInput"),
      sceneFilterBar: documentRef.getElementById("sceneFilterBar"),
      sceneBrowserCount: documentRef.getElementById("sceneBrowserCount"),
      sceneBrowserActive: documentRef.getElementById("sceneBrowserActive"),
      sceneCards: documentRef.getElementById("sceneCards"),
      sceneNote: documentRef.getElementById("sceneNote"),
      sceneGuidePanel: documentRef.getElementById("sceneGuidePanel"),
      slabThicknessControl: documentRef.getElementById("slabThicknessControl"),
      slabThicknessInput: documentRef.getElementById("slabThicknessInput"),
      slabThicknessOutput: documentRef.getElementById("slabThicknessOutput"),
      gridNxInput: documentRef.getElementById("gridNxInput"),
      gridNyInput: documentRef.getElementById("gridNyInput"),
      stabilityCflValue: documentRef.getElementById("stabilityCflValue"),
      stabilityResolutionValue: documentRef.getElementById("stabilityResolutionValue"),
      stabilityMediaValue: documentRef.getElementById("stabilityMediaValue"),
      stabilityEstimateValue: documentRef.getElementById("stabilityEstimateValue"),
      stabilityNote: documentRef.getElementById("stabilityNote"),
      configScaleOutput: documentRef.getElementById("configScaleOutput"),
      configGridOutput: documentRef.getElementById("configGridOutput"),
      configBoundaryOutput: documentRef.getElementById("configBoundaryOutput"),
      configCflOutput: documentRef.getElementById("configCflOutput"),
      configStabilityOutput: documentRef.getElementById("configStabilityOutput"),
      exportSceneBtn: documentRef.getElementById("exportSceneBtn"),
      importSceneBtn: documentRef.getElementById("importSceneBtn"),
      importSceneFileInput: documentRef.getElementById("importSceneFileInput"),
      copySceneUrlBtn: documentRef.getElementById("copySceneUrlBtn"),
      shareSceneUrlOutput: documentRef.getElementById("shareSceneUrlOutput"),
      reproStatus: documentRef.getElementById("reproStatus"),
      brushSizeControl: documentRef.getElementById("brushSizeControl"),
      brushToolControl: documentRef.getElementById("brushToolControl"),
      brushToolButtons: documentRef.querySelectorAll("[data-brush-tool]"),
      brushGeometryPanel: documentRef.getElementById("brushGeometryPanel"),
      brushGeometryInput: documentRef.getElementById("brushGeometryInput"),
      geometryWidthControl: documentRef.getElementById("geometryWidthControl"),
      geometryWidthInput: documentRef.getElementById("geometryWidthInput"),
      geometryHeightControl: documentRef.getElementById("geometryHeightControl"),
      geometryHeightInput: documentRef.getElementById("geometryHeightInput"),
      geometryRadiusControl: documentRef.getElementById("geometryRadiusControl"),
      geometryRadiusInput: documentRef.getElementById("geometryRadiusInput"),
      geometryInnerRadiusControl: documentRef.getElementById("geometryInnerRadiusControl"),
      geometryInnerRadiusInput: documentRef.getElementById("geometryInnerRadiusInput"),
      brushMenu: documentRef.getElementById("brushMenu"),
      brushMenuHint: documentRef.getElementById("brushMenuHint"),
      brushMenuCloseBtn: documentRef.getElementById("brushMenuCloseBtn"),
      brushMenuSizeInput: documentRef.getElementById("brushMenuSizeInput"),
      brushMenuSizeOutput: documentRef.getElementById("brushMenuSizeOutput"),
      brushMenuClearMaterialsBtn: documentRef.getElementById("brushMenuClearMaterialsBtn"),
      brushMenuClearFieldsBtn: documentRef.getElementById("brushMenuClearFieldsBtn"),
      boundaryMenu: documentRef.getElementById("boundaryMenu"),
      boundaryMenuHint: documentRef.getElementById("boundaryMenuHint"),
      boundaryMenuCloseBtn: documentRef.getElementById("boundaryMenuCloseBtn"),
      boundaryMenuInput: documentRef.getElementById("boundaryMenuInput"),
      simGuideSolver: documentRef.getElementById("simGuideSolver"),
      simGuideSource: documentRef.getElementById("simGuideSource"),
      simGuideBoundary: documentRef.getElementById("simGuideBoundary"),
      simGuideMaterial: documentRef.getElementById("simGuideMaterial"),
      simGuideCfl: documentRef.getElementById("simGuideCfl"),
      simGuideWarning: documentRef.getElementById("simGuideWarning"),
      inspectorKind: documentRef.getElementById("inspectorKind"),
      inspectorTitle: documentRef.getElementById("inspectorTitle"),
      inspectorDetails: documentRef.getElementById("inspectorDetails"),
      inspectorNote: documentRef.getElementById("inspectorNote"),
      inspectorEditBtn: documentRef.getElementById("inspectorEditBtn"),
      inspectorClearBtn: documentRef.getElementById("inspectorClearBtn"),
      summaryReflectanceOutput: documentRef.getElementById("summaryReflectanceOutput"),
      summaryTransmittanceOutput: documentRef.getElementById("summaryTransmittanceOutput"),
      summaryBalanceOutput: documentRef.getElementById("summaryBalanceOutput"),
      summaryAngleOutput: documentRef.getElementById("summaryAngleOutput"),
      fluxLeftOutput: documentRef.getElementById("fluxLeftOutput"),
      diagnosticAngleOutput: documentRef.getElementById("diagnosticAngleOutput"),
      reflectedPowerOutput: documentRef.getElementById("reflectedPowerOutput"),
      fluxRightOutput: documentRef.getElementById("fluxRightOutput"),
      reflectanceOutput: documentRef.getElementById("reflectanceOutput"),
      transmittanceOutput: documentRef.getElementById("transmittanceOutput"),
      colorbar: documentRef.querySelector(".colorbar"),
      colorbarTitle: documentRef.getElementById("colorbarTitle"),
      colorbarGradient: documentRef.getElementById("colorbarGradient"),
      colorbarMax: documentRef.getElementById("colorbarMax"),
      colorbarMid: documentRef.getElementById("colorbarMid"),
      colorbarMin: documentRef.getElementById("colorbarMin"),
      engineValue: documentRef.getElementById("engineValue"),
      canvasContextMenu: documentRef.getElementById("canvasContextMenu"),
      canvasContextMenuHint: documentRef.getElementById("canvasContextMenuHint"),
      canvasContextCloseBtn: documentRef.getElementById("canvasContextCloseBtn"),
      sourceMenu: documentRef.getElementById("sourceMenu"),
      sourceMenuTitle: documentRef.getElementById("sourceMenuTitle"),
      sourceMenuHint: documentRef.getElementById("sourceMenuHint"),
      sourceApplyBtn: documentRef.getElementById("sourceApplyBtn"),
      sourceDeleteBtn: documentRef.getElementById("sourceDeleteBtn"),
      sourceCloseBtn: documentRef.getElementById("sourceCloseBtn"),
      monitorMenu: documentRef.getElementById("monitorMenu"),
      monitorMenuTitle: documentRef.getElementById("monitorMenuTitle"),
      monitorMenuHint: documentRef.getElementById("monitorMenuHint"),
      monitorQuantityInput: documentRef.getElementById("monitorQuantityInput"),
      monitorXInput: documentRef.getElementById("monitorXInput"),
      monitorYInput: documentRef.getElementById("monitorYInput"),
      monitorLengthInput: documentRef.getElementById("monitorLengthInput"),
      monitorLengthOutput: documentRef.getElementById("monitorLengthOutput"),
      monitorAngleInput: documentRef.getElementById("monitorAngleInput"),
      monitorAngleOutput: documentRef.getElementById("monitorAngleOutput"),
      monitorApplyBtn: documentRef.getElementById("monitorApplyBtn"),
      monitorDeleteBtn: documentRef.getElementById("monitorDeleteBtn"),
      monitorCloseBtn: documentRef.getElementById("monitorCloseBtn"),
      customMonitorResults: documentRef.getElementById("customMonitorResults"),
    };
  }

  global.FdtdUiDom = Object.freeze({
    collectDomRefs,
    validateDomRefs,
  });
})(window);
