"use strict";

const COURANT = 0.1;
const VISUAL_COURANT_REFERENCE = 0.48;
const MAX_NUMERICAL_STEPS_PER_FRAME = 64;
const DEFAULT_GRID = { nx: 360, ny: 240 };
const DEFAULT_PORTRAIT_GRID = { nx: DEFAULT_GRID.ny, ny: DEFAULT_GRID.nx };
const PHONE_PORTRAIT_GRID = { nx: 208, ny: 384 };
const MAX_GRID = { nx: 1200, ny: 800 };
const MIN_CANVAS_DISPLAY_ASPECT = 0.5;
const MAX_CANVAS_DISPLAY_ASPECT = 6;
const MIN_CANVAS_DISPLAY_HEIGHT = 220;
const MAX_CANVAS_DISPLAY_HEIGHT = 1500;
const CANVAS_DISPLAY_VIEWPORT_FRACTION = 0.68;
const WASM_CORE_URL = "assets/wasm/fdtd-core.wasm?v=20260704-cpml-interior-fastpath-1";
const WASM_PAGE_BYTES = 65536;
const WASM_MAX_PAGES = 4096;
const FIELD_RENORMALIZE_HIGH = 1e12;
const FIELD_RENORMALIZE_TARGET = 1e3;
const DIAGNOSTIC_DFT_WINDOW = 512;
const BIANISOTROPY_KAPPA_LIMIT = 0.85;
const THEME_STORAGE_KEY = "fdtdTheme";
const UI_DEPTH_STORAGE_KEY = "fdtdUiDepth";

Object.assign(globalThis, {
  COURANT,
  VISUAL_COURANT_REFERENCE,
  MAX_NUMERICAL_STEPS_PER_FRAME,
  DEFAULT_GRID,
  DEFAULT_PORTRAIT_GRID,
  PHONE_PORTRAIT_GRID,
  MAX_GRID,
  MIN_CANVAS_DISPLAY_ASPECT,
  MAX_CANVAS_DISPLAY_ASPECT,
  MIN_CANVAS_DISPLAY_HEIGHT,
  MAX_CANVAS_DISPLAY_HEIGHT,
  CANVAS_DISPLAY_VIEWPORT_FRACTION,
  WASM_CORE_URL,
  WASM_PAGE_BYTES,
  WASM_MAX_PAGES,
  FIELD_RENORMALIZE_HIGH,
  FIELD_RENORMALIZE_TARGET,
  DIAGNOSTIC_DFT_WINDOW,
  BIANISOTROPY_KAPPA_LIMIT,
  THEME_STORAGE_KEY,
  UI_DEPTH_STORAGE_KEY,
});
