"use strict";

const materialNames = {
  custom: "Custom ε, μ",
  dielectric: "Dielectric",
  pec: "PEC",
  lossy: "Loss",
  erase: "Erase",
};

const localizedSourceShapes = new Set([
  "gaussianSpot",
  "pointDipole",
  "dipole",
  "circularDipoleCw",
  "circularDipoleCcw",
  "janusDipole",
  "huygens",
  "quadrupole",
  "multipole",
]);
const inPlaneElectricCurrentShapes = new Set(["inPlaneElectricDipole"]);
const currentSourceShapes = new Set(["point", ...localizedSourceShapes]);
const incidentFieldSourceShapes = new Set(["line", "gaussianProfile", "evanescentLine"]);
const lineLikeIncidentSourceShapes = new Set(["line", "evanescentLine"]);
const circularDipoleSourceShapes = new Set(["circularDipoleCw", "circularDipoleCcw"]);

const sourceShapeLabels = {
  point: "Jz filament",
  line: "Plane wave",
  gaussianProfile: "Gaussian line",
  gaussianSpot: "Gaussian Jz patch",
  pointDipole: "Point electric dipole",
  dipole: "Jz dipole pair",
  circularDipoleCw: "Circular dipole +90 deg",
  circularDipoleCcw: "Circular dipole -90 deg",
  janusDipole: "Janus dipole",
  huygens: "Huygens source",
  quadrupole: "Jz quadrupole pattern",
  multipole: "Jz multipole pattern",
  inPlaneElectricDipole: "In-plane electric dipole",
  evanescentLine: "Evanescent line",
};

const defaultSourceConfig = {
  type: "sine",
  shape: "point",
  frequency: COURANT / 20,
  amplitude: 0.55,
  xLambda: 1.2,
  yLambda: 3,
  widthLambda: 0.35,
  angleDeg: 0,
  phaseDeg: 0,
  multipoleOrder: 3,
  multipolePhase: "cos",
};

const sceneDescriptions = {
  empty: "Blank domain. Use right-click menus to add sources, boundaries, and drawn materials.",
  planeWaveAir: "Atlas 1: homogeneous air with a continuous line source.",
  planeWaveDielectric: "Atlas 2: full dielectric domain, n = 1.5, to show shorter wavelength and slower phase velocity.",
  gaussianPulseAir: "Atlas 3: Gaussian pulse in free space with absorbing boundaries.",
  twoSourceInterference: "Atlas 4: two coherent point Jz sources separated by about 1.5 lambda0.",
  frequencyBeat: "Atlas 5: two nearby CW frequencies to reveal a beat envelope.",
  singleSlit: "Atlas 6: PEC screen with one subwavelength slit.",
  doubleSlit: "Atlas 7: PEC screen with two slits for Young-type interference.",
  circularAperture: "Atlas 8: 2D circular aperture cut into a PEC screen.",
  teTmComparison: "Atlas 9: TEz/TMz comparison on the same air-dielectric interface, using a dual-polarization angular sweep.",
  evanescentWave: "Atlas 11: isolated evanescent wave with k_parallel greater than k0 and exponential decay away from the source line.",
  poyntingPlaneWave: "Atlas 10: oblique plane wave shown as Poynting flux with vector arrows.",
  pmlAbsorption: "Atlas 12: pulsed source aimed at the absorbing boundary for reflection checks.",
  normalInterface: "Atlas 13: air to n = 1.5 vertical interface.",
  obliqueRefraction: "Atlas 14: oblique Gaussian beam on an air-dielectric interface.",
  brewsterTm: "Atlas 15: p/TM-polarized incidence on an air-dielectric interface near the Brewster angle.",
  brewsterTeTm: "Atlas 16: TE/TM Brewster comparison with dual numerical angular sweeps and analytic Fresnel references.",
  totalInternalReflection: "Atlas 17: beam incident from n = 1.5 toward air above the critical angle.",
  frustratedTir: "Atlas 18: two high-index regions separated by a narrow air gap.",
  quarterWaveCoating: "Atlas 19: air, quarter-wave coating, and n = 1.5 substrate.",
  braggMirror: "Atlas 20: six-pair n = 1.5 / n = 2.5 Bragg mirror.",
  lossyInterface: "Atlas 21: air to n = 1.5 + 0.1i interface.",
  anisotropicInterface: "Atlas 22: right-hand medium with eps_x != eps_y.",
  jzDipole: "Atlas 23: localized electric Jz dipole in air.",
  inPlaneDipole: "Atlas 24: in-plane electric Jx/Jy dipole using the Hz solver.",
  mzDipole: "Atlas 25: localized magnetic Mz dipole using the Hz solver.",
  dipoleSubstrate: "Atlas 26: Jz dipole close to a dielectric substrate.",
  dipoleNearPec: "Atlas 27: Jz dipole close to a PEC mirror.",
  huygensRadiator: "Atlas 28: analytic Huygens-like source for directional radiation.",
  circularDipole: "Atlas 29: quadrature circular dipole source.",
  janusDipole: "Atlas 30: Janus source near a dielectric waveguide.",
  dipoleArray: "Atlas 31: equal-phase dipole array.",
  phasedDipoleArray: "Atlas 32: progressive temporal phase per dipole for beam steering.",
  apertureRadiator: "Atlas 33: source behind a PEC slot aperture.",
  nearFarFieldNtff: "Atlas 34: near-field dipole radiation with normalized equivalence-principle NTFF angular pattern.",
  slabWaveguide: "Atlas 35: high-index slab guide with a Gaussian line source approximation.",
  multimodeSlab: "Atlas 36: wider slab guide for multimode beating.",
  lossyGuide: "Atlas 37: lossy high-index guide.",
  waveguideBend: "Atlas 38: 90-degree dielectric waveguide bend using a quarter-ring path.",
  taperWaveguide: "Atlas 39: width taper from narrow to wide guide.",
  widthStepWaveguide: "Atlas 40: abrupt waveguide width step.",
  directionalCoupler: "Atlas 41: two parallel guides separated by a small gap.",
  mmiWaveguide: "Atlas 42: narrow input feeding a wider multimode section.",
  machZehnder: "Atlas 43: qualitative Mach-Zehnder interferometer with two dielectric arms.",
  guideScatterer: "Atlas 44: small dielectric scatterer beside a guide.",
  microstrip: "Atlas 45: qualitative microstrip cross-section with PEC strip, dielectric substrate, and ground plane.",
  stubResonator: "Atlas 46: side stub attached to a straight guide.",
  fabryPerot: "Atlas 47: dielectric cavity placed between two Bragg reflectors.",
  fabryPerotStanding: "Atlas 48: Fabry-Perot resonator driven near a standing-wave condition.",
  ringResonator: "Atlas 49: dielectric ring coupled to one bus waveguide.",
  addDropRing: "Atlas 50: dielectric ring coupled to input and drop buses.",
  racetrackResonator: "Atlas 51: elongated racetrack resonator side-coupled to a bus waveguide.",
  dielectricCavity: "Atlas 52: high-index disk with an internal dipole source.",
  pecCavity: "Atlas 53: PEC half-wave box cavity with a point source.",
  quarterWaveCavity: "Atlas 54: shorted quarter-wave stub cavity coupled to a dielectric guide.",
  qRingdown: "Atlas 55: pulsed cavity ringdown with an estimated decay Q from the analysis energy trace.",
  purcell2d: "Atlas 56: dipole in a high-index 2D cavity with a comparative Q/Aeff Purcell proxy.",
  betaFactor: "Atlas 57: dipole coupled to a slab guide with an estimated guided-flux beta factor.",
  degenerateModes: "Atlas 58: symmetric disk cavity excited off-center to reveal near-degenerate spectral peaks.",
  pecCylinder: "Atlas 59: PEC cylinder under plane-wave illumination.",
  dielectricCylinder: "Atlas 60: n = 2 cylinder scattering.",
  mieCylinder: "Atlas 61: high-index cylinder for Mie-like resonances.",
  rcsCylinder: "Atlas 62: PEC cylinder with incident-background subtraction and estimated 2D scattering width.",
  lossyCylinder: "Atlas 63: absorbing dielectric cylinder.",
  dielectricDimer: "Atlas 64: two high-index cylinders with a narrow gap.",
  kerker2d: "Atlas 65: high-index cylinder showing forward/backward scattering contrast with the 2D NTFF observable.",
  multipleScattering: "Atlas 66: deterministic random cluster of cylinders.",
  weakLocalization: "Atlas 67: many weak inclusions for multiple scattering.",
  finiteConductivity: "Atlas 70: conductive half-space using an explicit J = sigma E update to show skin-depth attenuation.",
  drudeMetal: "Atlas 71: Drude ADE metal with plasma frequency and damping.",
  lorentzMedium: "Atlas 72: Lorentz ADE resonant dielectric slab.",
  debyeDielectric: "Atlas 73: Debye relaxation dielectric slab.",
  plasmaCutoff: "Atlas 74: collisionless plasma slab near cutoff.",
  enzSlab: "Atlas 75: passive Drude ADE epsilon-near-zero slab tuned near the source frequency.",
  anisotropicMedium: "Atlas 76: anisotropic block, eps_x = 4, eps_y = 2.",
  hyperbolicMedium: "Atlas 77: constant anisotropic medium with eps_x > 0 and eps_y < 0.",
  chiralMedium: "Atlas 78: six-component 2D chiral-medium proxy with passivity-limited local magnetoelectric coupling.",
  bianisotropicMedium: "Atlas 79: six-component 2D bianisotropic block with anisotropic eps/mu and local magnetoelectric coupling.",
  gyrotropicMedium: "Atlas 80: qualitative gyrotropic epsilon tensor in the Hz solver, using eps_xy = +g and eps_yx = -g.",
  braggStack: "Atlas 81: 1D periodic Bragg stack.",
  photonicCrystal: "Atlas 82: square lattice of high-index rods with a reduced plane-wave Bloch-k band estimate.",
  phcPointDefect: "Atlas 83: photonic crystal with one missing central rod, finite-cavity leakage proxy, and reduced Bloch bands.",
  phcWaveguide: "Atlas 84: photonic crystal line-defect waveguide with reduced plane-wave Bloch-k reference.",
  phcOptimizedCavity: "Atlas 85: L3-like photonic-crystal cavity with locally shifted/tapered rods, Q proxy, and reduced Bloch bands.",
  phcDisorder: "Atlas 86: photonic crystal with deterministic positional disorder.",
  phcDarkMode: "Atlas 87: symmetric PhC defect excited with an antisymmetric dark-mode source, leakage/Q proxy, and reduced Bloch bands.",
  quasiBic: "Atlas 88: weakly symmetry-broken PhC defect showing quasi-BIC leakage with reduced Bloch bands and local asymmetry proxies.",
  symmetryProtectedBic: "Atlas 89: symmetry-protected BIC proxy using a symmetric PhC cavity, odd excitation, and reduced Bloch bands.",
  fanoResonator: "Atlas 90: straight guide with a side-coupled dielectric resonator.",
  sshTrivial: "Atlas 91: SSH chain with d1 > d2 and analytic Bloch winding/gap reference.",
  sshTopological: "Atlas 92: SSH chain with d1 < d2 and analytic Bloch winding/gap reference.",
  sshInterface: "Atlas 93: interface between two SSH dimerizations with expected edge-state reference.",
  sshDisorder: "Atlas 94: SSH interface with deterministic positional disorder and analytic clean-limit Bloch reference.",
  nonHermitianSsh: "Atlas 95: SSH chain with alternating gain/loss, saturable-gain stabilization, and reduced non-Hermitian gap proxy.",
  honeycombLattice: "Atlas 96: honeycomb-like dimer lattice for valley-photonic demonstrations.",
  valleyHall: "Atlas 97: two inverted honeycomb domains forming a straight Valley-Hall interface.",
  valleyHallBend: "Atlas 98: Valley-Hall interface with a 90-degree bend.",
  topologicalPumping: "Atlas 99: modulated SSH chain showing qualitative Thouless-pump-like transport.",
  topologyDefect: "Atlas 100: Valley-Hall interface with a strong defect placed on the channel.",
  sppInterface: "Atlas 101: Drude metal-dielectric interface excited by a near-field dipole.",
  sppGrating: "Atlas 102: shallow Drude grating for qualitative SPP coupling.",
  localizedPlasmon: "Atlas 103: localized plasmon on a Drude nanodisk.",
  plasmonicDimer: "Atlas 104: two Drude disks with a narrow hot gap.",
  metasurfacePhaseBars: "Atlas 105: phase-gradient metasurface approximated by dielectric bars.",
  perfectAbsorber: "Atlas 106: impedance-matched lossy sheet backed by PEC, with absorptance estimated from line monitors.",
  negativeIndexSlab: "Atlas 107: passive Drude ADE epsilon/mu slab tuned to a negative-index band.",
  superlensSlab: "Atlas 108: passive Drude ADE epsilon/mu slab as a qualitative superlens analogue.",
  hyperlens: "Atlas 109: passive dispersive hyperlens analogue using a radial/tangential Drude tensor in the Hz solver.",
  enzEmitter: "Atlas 110: dipole close to a passive Drude ENZ slab.",
  kerrSlab: "Atlas 111: instantaneous Kerr slab with epsilon updated from normalized field intensity.",
  shgSlab: "Atlas 112: chi2 nonlinear slab using a polarization-current source for second-harmonic generation.",
  thgSlab: "Atlas 113: chi3 nonlinear slab using a polarization-current source for third-harmonic generation.",
  spmKerrPulse: "Atlas 114: pulsed Kerr guide/slab for qualitative self-phase modulation and spectral sideband broadening.",
  kerrBistableCavity: "Atlas 115: driven Kerr ring-cavity proxy for optical bistability with an optional bidirectional amplitude sweep.",
  vo2SwitchingSlab: "Atlas 116: VO2-like phase-change slab with intensity threshold, hysteresis, and finite switching time.",
  pcmMemoryCell: "Atlas 117: small phase-change memory cell embedded in a guide; the switched state persists after the field is cleared.",
  saturableAbsorber: "Atlas 118: bleachable absorber analogue using the phase-state model to reduce loss above threshold.",
  allOpticalSwitch: "Atlas 119: Mach-Zehnder-like guide with a nonlinear control section for qualitative all-optical switching.",
  nonlinearLimiter: "Atlas 120: intensity-triggered lossy phase-change section for qualitative optical limiting.",
  temporalInterface: "Atlas 121: finite dielectric interface with nearly uniform temporal epsilon modulation and reduced Floquet sideband S_m estimate.",
  temporalSlab: "Atlas 122: finite slab with uniform-in-space sinusoidal epsilon modulation and reduced time-refraction sideband S_m estimate.",
  temporalModulation: "Atlas 123: region tagged with sinusoidal epsilon modulation and reduced Floquet sideband analysis.",
  temporalCrystal: "Atlas 124: extended time-periodic dielectric region with reduced Floquet sideband analysis.",
  modulatedGuide: "Atlas 125: slab waveguide with a finite temporally modulated section and reduced S_m sideband readout.",
  travelingModulation: "Atlas 126: guide section tagged with traveling epsilon modulation and forward/reverse transmission check.",
  temporalIsolator: "Atlas 127: traveling-modulation guide section with approximate isolation and reduced Floquet sideband S_m readout.",
  modulatedRing: "Atlas 128: side-coupled ring resonator with temporally modulated refractive index and sideband S_m estimate.",
  floquetResonators: "Atlas 129: coupled modulated resonators with reduced Floquet splitting and sideband S_m analysis.",
  syntheticFrequency: "Atlas 130: chain of modulated resonators as a synthetic-frequency analogue with reduced sideband S_m analysis.",
  ptSymmetricCoupler: "Atlas 131: PT-symmetric coupled guides with balanced gain/loss, saturable gain, gamma sweep, and reduced modal EP estimate.",
  exceptionalPointCoupler: "Atlas 132: PT-symmetric coupled-guide exceptional-point proxy with gamma sweep and reduced 2x2 modal coalescence estimate.",
  nonHermitianSkin: "Atlas 133: non-Hermitian skin-effect analogue using a biased gain/loss SSH chain.",
  bicKerr: "Atlas 134: symmetry-protected BIC-style PhC cavity with a Kerr nonlinear defect region and reduced Bloch-k leakage/band proxy.",
  bicEnz: "Atlas 135: BIC-style PhC cavity side-coupled to a passive Drude ENZ inclusion with reduced Bloch-k leakage/band proxy.",
  janusTopologicalGuide: "Atlas 136: Janus source coupled into a qualitative Valley-Hall topological guide.",
  huygensCavity: "Atlas 137: Huygens source coupled to a dielectric cavity/resonator.",
  topologyTemporalMod: "Atlas 138: Valley-Hall channel with a temporally modulated segment and reduced Floquet sideband readout.",
  nonreciprocalValleyHall: "Atlas 139: Valley-Hall channel with traveling modulation, approximate isolation, and reduced sideband S_m readout.",
  spaceTimeCrystal: "Atlas 140: space-time crystal analogue with traveling epsilon modulation and reduced Floquet sideband readout.",
};

const BOUNDARY_SIDES = ["left", "right", "top", "bottom"];
const scatteringAnalysisPresets = new Set([
  "pecCylinder",
  "dielectricCylinder",
  "mieCylinder",
  "rcsCylinder",
  "lossyCylinder",
  "dielectricDimer",
  "kerker2d",
  "multipleScattering",
  "weakLocalization",
]);
const resonatorAnalysisPresets = new Set([
  "fabryPerot",
  "fabryPerotStanding",
  "ringResonator",
  "addDropRing",
  "dielectricCavity",
  "pecCavity",
  "phcOptimizedCavity",
  "phcDarkMode",
  "quasiBic",
  "symmetryProtectedBic",
  "qRingdown",
  "purcell2d",
  "betaFactor",
  "degenerateModes",
  "modulatedRing",
  "floquetResonators",
  "syntheticFrequency",
  "exceptionalPointCoupler",
  "bicKerr",
  "bicEnz",
  "huygensCavity",
]);
const purcellAnalysisPresets = new Set(["purcell2d"]);
const betaAnalysisPresets = new Set(["betaFactor"]);
const degenerateAnalysisPresets = new Set(["degenerateModes", "exceptionalPointCoupler"]);
const leakageAnalysisPresets = new Set(["phcDarkMode", "quasiBic", "symmetryProtectedBic", "bicKerr", "bicEnz"]);
const phcBlochAnalysisPresets = new Set([
  "photonicCrystal",
  "phcPointDefect",
  "phcWaveguide",
  "phcOptimizedCavity",
  "phcDarkMode",
  "quasiBic",
  "symmetryProtectedBic",
  "bicKerr",
  "bicEnz",
]);
const ptModalAnalysisPresets = new Set(["ptSymmetricCoupler", "exceptionalPointCoupler"]);
const sshBlochAnalysisPresets = new Set(["sshTrivial", "sshTopological", "sshInterface", "sshDisorder", "nonHermitianSsh"]);
const absorptionAnalysisPresets = new Set(["perfectAbsorber"]);
const negativeIndexAnalysisPresets = new Set(["negativeIndexSlab", "superlensSlab"]);
const bianisotropyAnalysisPresets = new Set(["chiralMedium", "bianisotropicMedium"]);
const harmonicAnalysisPresets = new Set(["shgSlab", "thgSlab"]);
const nonlinearAnalysisPresets = new Set([
  "shgSlab",
  "thgSlab",
  "spmKerrPulse",
  "kerrBistableCavity",
  "saturableAbsorber",
  "allOpticalSwitch",
  "nonlinearLimiter",
  "vo2SwitchingSlab",
  "pcmMemoryCell",
  "bicKerr",
]);
const temporalFloquetAnalysisPresets = new Set([
  "temporalInterface",
  "temporalSlab",
  "temporalModulation",
  "temporalCrystal",
  "modulatedGuide",
  "travelingModulation",
  "temporalIsolator",
  "modulatedRing",
  "floquetResonators",
  "syntheticFrequency",
  "topologyTemporalMod",
  "nonreciprocalValleyHall",
  "spaceTimeCrystal",
]);
const phaseChangeAnalysisPresets = new Set([
  "saturableAbsorber",
  "allOpticalSwitch",
  "nonlinearLimiter",
  "vo2SwitchingSlab",
  "pcmMemoryCell",
]);
const defaultBoundarySides = {
  left: "absorbing",
  right: "absorbing",
  top: "absorbing",
  bottom: "absorbing",
};
const boundarySideLabels = {
  left: "Left",
  right: "Right",
  top: "Top",
  bottom: "Bottom",
};
